apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbcenter-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/zanis/data/test-apps/dbcenter
